### ISSUE TITLE
Investigate the Warning Message due to ExternalModuleDependancies section in PSD1 file 

### ISSUE THREAD

**Issue by eliassal** [kilasuit/PSISE_Addons#7]
Ryan, after issuing the following command, 
`Install-Module -Name ISE_Cew -Scope CurrentUser;`

setup was successful  but I got the following warning:

> WARNING: The externally managed, dependent module 'System.Collections.Hashtable' is not installed on this computer. To use the current module 
> 'ISE_Cew', ensure that its dependent module 'System.Collections.Hashtable' is installed.

Thanks for your help

**Comment by eliassal** [comment]
Also, after closing and reopening ISE, nothing is added, so how this module can be used, thanks

**Comment by kilasuit** [comment]
I've been investigating the Warning that occurs and I am currently testing a fix for this which I'll hopefully have ready in the next day or two.

Regarding how to use the module there is a file [ProfileExample.txt](https://github.com/kilasuit/ISE_Cew/blob/master/ISE_Cew/ProfileExample.txt) which has an example of what you can add to your profile which I realised was missing from this repo and I've added that in the latest commit here
f597bc40194eae56e4e5161fe2182a9562ab7a47

**Comment by kilasuit** [comment]
I chose not to be forceful of changes to ISE, hence the example profile additions, although you can once the module has been imported you can always run any of the Save-\* functions as required.

**Comment by kilasuit** [comment]
#wontFix
